apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tire: db
  name: redis
spec:
  containers:
  - image: redis:alpine
    name: redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
